# Generated by Django 5.2 on 2025-10-19 02:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite_stock', models.IntegerField(default=0)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='inventory.categorie')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_terminal', models.CharField(help_text='Nom du terminal ou responsable MAUI', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description du terminal ou notes')),
                ('numero_serie', models.CharField(help_text="Numéro de série unique pour l'authentification MAUI", max_length=50, unique=True)),
                ('cle_api', models.CharField(default=uuid.uuid4, help_text='Clé API générée automatiquement', max_length=100, unique=True)),
                ('est_actif', models.BooleanField(default=True, help_text='Le client peut-il se connecter?')),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('derniere_activite', models.DateTimeField(blank=True, null=True)),
                ('version_app_maui', models.CharField(blank=True, help_text="Version de l'application MAUI", max_length=20)),
                ('derniere_adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Notes internes')),
                ('compte_proprietaire', models.ForeignKey(help_text='Compte utilisateur propriétaire de ce client MAUI', on_delete=django.db.models.deletion.CASCADE, related_name='clients_maui', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client MAUI',
                'verbose_name_plural': 'Clients MAUI',
                'ordering': ['-derniere_connexion', 'nom_terminal'],
            },
        ),
        migrations.CreateModel(
            name='Commercant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(help_text="Nom de l'entreprise ou du commerçant", max_length=200)),
                ('nom_responsable', models.CharField(help_text='Nom du responsable principal', max_length=100)),
                ('email', models.EmailField(help_text='Email de contact principal', max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.TextField(blank=True, help_text="Adresse principale de l'entreprise")),
                ('numero_registre_commerce', models.CharField(blank=True, help_text='Numéro de registre de commerce', max_length=50)),
                ('numero_fiscal', models.CharField(blank=True, help_text="Numéro d'identification fiscale", max_length=50)),
                ('est_actif', models.BooleanField(default=True, help_text='Le commerçant peut-il accéder au système?')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('type_abonnement', models.CharField(choices=[('GRATUIT', 'Gratuit (limité)'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('ENTREPRISE', 'Entreprise')], default='GRATUIT', max_length=50)),
                ('max_boutiques', models.IntegerField(default=1, help_text='Nombre maximum de boutiques autorisées')),
                ('limite_articles_par_boutique', models.IntegerField(default=100, help_text="Nombre maximum d'articles par boutique")),
                ('notes_admin', models.TextField(blank=True, help_text="Notes internes pour l'administration")),
                ('user', models.OneToOneField(help_text='Compte utilisateur Django associé', on_delete=django.db.models.deletion.CASCADE, related_name='profil_commercant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commerçant',
                'verbose_name_plural': 'Commerçants',
                'ordering': ['nom_entreprise'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée de stock'), ('SORTIE', 'Sortie de stock'), ('AJUSTEMENT', 'Ajustement'), ('VENTE', 'Vente')], max_length=20)),
                ('quantite', models.IntegerField()),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='inventory.article')),
            ],
            options={
                'ordering': ['-date_mouvement'],
            },
        ),
        migrations.CreateModel(
            name='ScanRecent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_scan', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.article')),
            ],
            options={
                'ordering': ['-date_scan'],
            },
        ),
        migrations.CreateModel(
            name='SessionClientMaui',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_session', models.CharField(max_length=100, unique=True)),
                ('adresse_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('version_app', models.CharField(blank=True, max_length=50)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('est_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='inventory.client')),
            ],
            options={
                'verbose_name': 'Session Client MAUI',
                'verbose_name_plural': 'Sessions Clients MAUI',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=50, unique=True)),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paye', models.BooleanField(default=False)),
                ('mode_paiement', models.CharField(choices=[('CASH', 'Espèces'), ('CARD', 'Carte bancaire'), ('MOBILE', 'Paiement mobile')], max_length=50)),
                ('adresse_ip_client', models.GenericIPAddressField(blank=True, help_text='Adresse IP du client MAUI', null=True)),
                ('version_app_maui', models.CharField(blank=True, help_text="Version de l'app MAUI utilisée", max_length=50)),
                ('client_maui', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='inventory.client')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-date_vente'],
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.article')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='inventory.vente')),
            ],
            options={
                'verbose_name': 'Ligne de vente',
                'verbose_name_plural': 'Lignes de vente',
            },
        ),
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom de la boutique', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description de la boutique')),
                ('type_commerce', models.CharField(choices=[('PHARMACIE', 'Pharmacie'), ('BAR', 'Bar/Café'), ('ALIMENTATION', 'Alimentation générale'), ('SUPERMARCHE', 'Supermarché'), ('BOUTIQUE', 'Boutique générale'), ('KIOSQUE', 'Kiosque'), ('HABILLEMENT', 'Habillement'), ('ELECTRONIQUE', 'Électronique'), ('AUTRE', 'Autre')], default='BOUTIQUE', max_length=50)),
                ('adresse', models.TextField(blank=True, help_text='Adresse de la boutique')),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('code_boutique', models.CharField(help_text="Code unique pour identifier la boutique dans l'API", max_length=50, unique=True)),
                ('cle_api_boutique', models.CharField(default=uuid.uuid4, help_text='Clé API unique pour cette boutique', max_length=100, unique=True)),
                ('est_active', models.BooleanField(default=True, help_text='La boutique est-elle active?')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('devise', models.CharField(default='CDF', max_length=10)),
                ('commercant', models.ForeignKey(help_text='Commerçant propriétaire de cette boutique', on_delete=django.db.models.deletion.CASCADE, related_name='boutiques', to='inventory.commercant')),
            ],
            options={
                'verbose_name': 'Boutique',
                'verbose_name_plural': 'Boutiques',
                'ordering': ['commercant__nom_entreprise', 'nom'],
                'unique_together': {('commercant', 'nom')},
            },
        ),
    ]
