# Generated by Django 5.2 on 2025-10-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_article_boutique'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='boutique',
            name='email',
            field=models.EmailField(blank=True, help_text='Email de contact de la boutique', max_length=254),
        ),
    ]
