# Generated by Django 5.2 on 2025-10-19 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_boutique_code_postal_boutique_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='alerte_stock_bas',
            field=models.IntegerField(default=5, help_text="Seuil d'alerte pour stock bas"),
        ),
        migrations.AddField(
            model_name='categorie',
            name='boutique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='inventory.boutique'),
        ),
        migrations.AddField(
            model_name='client',
            name='boutique',
            field=models.ForeignKey(blank=True, help_text='Boutique à laquelle ce terminal est associé', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='inventory.boutique'),
        ),
    ]
