# Generated by Django 5.2 on 2025-10-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_boutique_alerte_stock_bas_categorie_boutique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='est_actif',
            field=models.BooleanField(default=True, help_text="L'article est-il actif?"),
        ),
    ]
