# Generated by Django 5.2 on 2025-10-30 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_article_est_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='boutique',
            field=models.ForeignKey(blank=True, help_text='Boutique à laquelle cette vente appartient', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='inventory.boutique'),
        ),
    ]
