# Generated by Django - Amélioration MouvementStock

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_vente_boutique'),
    ]

    operations = [
        # Ajouter le type RETOUR
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_mouvement',
            field=models.CharField(
                choices=[
                    ('ENTREE', 'Entrée de stock'),
                    ('SORTIE', 'Sortie de stock'),
                    ('AJUSTEMENT', 'Ajustement'),
                    ('VENTE', 'Vente'),
                    ('RETOUR', 'Retour client')
                ],
                max_length=20
            ),
        ),
        # Améliorer le champ quantite avec help_text
        migrations.AlterField(
            model_name='mouvementstock',
            name='quantite',
            field=models.IntegerField(help_text='Négatif pour sortie, positif pour entrée'),
        ),
        # Ajouter stock_avant
        migrations.AddField(
            model_name='mouvementstock',
            name='stock_avant',
            field=models.IntegerField(
                blank=True,
                help_text='Stock avant le mouvement',
                null=True
            ),
        ),
        # Ajouter stock_apres
        migrations.AddField(
            model_name='mouvementstock',
            name='stock_apres',
            field=models.IntegerField(
                blank=True,
                help_text='Stock après le mouvement',
                null=True
            ),
        ),
        # Ajouter reference_document
        migrations.AddField(
            model_name='mouvementstock',
            name='reference_document',
            field=models.CharField(
                blank=True,
                help_text='Numéro de facture, bon de livraison, etc.',
                max_length=100
            ),
        ),
        # Ajouter utilisateur
        migrations.AddField(
            model_name='mouvementstock',
            name='utilisateur',
            field=models.CharField(
                blank=True,
                help_text="Nom d'utilisateur ou device_serial",
                max_length=100
            ),
        ),
        # Améliorer les Meta options
        migrations.AlterModelOptions(
            name='mouvementstock',
            options={
                'ordering': ['-date_mouvement'],
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock'
            },
        ),
        # Ajouter les index pour les performances
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['article', 'date_mouvement'], name='mouvement_article_date_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['type_mouvement'], name='mouvement_type_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['reference_document'], name='mouvement_ref_idx'),
        ),
    ]
