# Generated by Django 5.2 on 2025-11-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_ameliorer_mouvementstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='pos_autorise',
            field=models.BooleanField(default=True),
        ),
    ]
