# Generated by Django 5.2 on 2025-12-01 23:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_boutique_pos_autorise'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rapport', models.DateTimeField(default=django.utils.timezone.now)),
                ('detail', models.TextField(max_length=500)),
                ('depense', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('devise', models.CharField(default='CDF', max_length=10)),
                ('est_synchronise', models.BooleanField(default=True)),
                ('id_backend', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_caisse', to='inventory.boutique')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_caisse', to='inventory.client')),
            ],
            options={
                'verbose_name': 'Rapport de caisse',
                'verbose_name_plural': 'Rapports de caisse',
                'ordering': ['-date_rapport', '-created_at'],
            },
        ),
    ]
