# Generated by Django 5.2 on 2025-12-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rapportcaisse'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportcaisse',
            name='date_application_depense',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rapportcaisse',
            name='depense_appliquee',
            field=models.BooleanField(default=False),
        ),
    ]
