# Generated by Django 5.2 on 2025-12-03 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_rapportcaisse_date_application_depense_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleNegocie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_article', models.CharField(max_length=100)),
                ('montant_negocie', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devise', models.CharField(default='CDF', max_length=10)),
                ('date_operation', models.DateTimeField()),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('reference_vente', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negociations', to='inventory.article')),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_negocies', to='inventory.boutique')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_negocies', to='inventory.client')),
            ],
            options={
                'ordering': ['-date_operation', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetourArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_article', models.CharField(max_length=100)),
                ('montant_retourne', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devise', models.CharField(default='CDF', max_length=10)),
                ('date_operation', models.DateTimeField()),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('reference_vente', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retours', to='inventory.article')),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retours_articles', to='inventory.boutique')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retours_articles', to='inventory.client')),
            ],
            options={
                'ordering': ['-date_operation', '-created_at'],
            },
        ),
    ]
