# Generated by Django 5.2 on 2025-12-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_vente_date_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='derniere_lecture_articles_negocies',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boutique',
            name='derniere_lecture_rapports_caisse',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boutique',
            name='derniere_lecture_retours_articles',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
