# Generated by Django 5.2 on 2025-12-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_boutique_derniere_lecture_articles_negocies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlenegocie',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='retourarticle',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
