# Generated by Django 5.2 on 2025-12-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_articlenegocie_quantite_retourarticle_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutique',
            name='type_commerce',
            field=models.CharField(choices=[('PHARMACIE', 'Pharmacie'), ('ALIMENTATION', 'Alimentation générale'), ('SUPERMARCHE', 'Supermarché'), ('BOUTIQUE', 'Boutique générale'), ('KIOSQUE', 'Kiosque'), ('BAR', 'Bar/Café'), ('RESTAURANT', 'Restaurant / Fast-food'), ('HABILLEMENT', 'Habillement / Friperie'), ('COIFFURE_BEAUTE', 'Salon de coiffure / Beauté'), ('ELECTRONIQUE', 'Appareils électroniques / Accessoires'), ('TELEPHONIE_MOBILE', 'Téléphonie / Mobile Money'), ('QUINCAILLERIE', 'Quincaillerie'), ('SERVICES_BUREAU', 'Services bureautiques / Cybercafé'), ('AUTRE', 'Autre')], default='BOUTIQUE', max_length=50),
        ),
    ]
