# Generated by Django 5.2 on 2025-12-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_boutique_type_commerce'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_suppression',
            field=models.DateTimeField(blank=True, help_text='Date de désactivation/suppression pour sync MAUI', null=True),
        ),
    ]
