# Generated by Django 5.2 on 2025-12-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_add_date_suppression_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='numero_facture',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
