# Generated by Django 5.2 on 2025-12-18 23:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_vente_numero_facture'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenteRejetee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vente_uid', models.CharField(db_index=True, help_text='Numéro de facture/UID de la vente rejetée', max_length=100)),
                ('date_tentative', models.DateTimeField(default=django.utils.timezone.now, help_text='Date de la tentative de synchronisation')),
                ('date_vente_originale', models.DateTimeField(blank=True, help_text='Date originale de la vente côté client', null=True)),
                ('donnees_vente', models.JSONField(help_text='Snapshot complet des données de vente envoyées')),
                ('raison_rejet', models.CharField(choices=[('INSUFFICIENT_STOCK', 'Stock insuffisant'), ('ARTICLE_NOT_FOUND', 'Article non trouvé'), ('PRIX_MODIFIE', 'Prix modifié'), ('TOTAL_INCOHERENT', 'Total incohérent'), ('BOUTIQUE_MISMATCH', 'Boutique non autorisée'), ('DUPLICATE', 'Vente déjà existante'), ('INVALID_FORMAT', 'Format invalide'), ('OTHER', 'Autre erreur')], default='OTHER', max_length=50)),
                ('message_erreur', models.TextField(help_text="Message d'erreur détaillé")),
                ('article_concerne_id', models.IntegerField(blank=True, help_text="ID de l'article concerné si applicable", null=True)),
                ('article_concerne_nom', models.CharField(blank=True, max_length=100)),
                ('stock_demande', models.IntegerField(blank=True, null=True)),
                ('stock_disponible', models.IntegerField(blank=True, null=True)),
                ('action_requise', models.CharField(choices=[('NOTIFY_USER', "Notifier l'utilisateur"), ('NOTIFY_MANAGER', 'Notifier le gérant'), ('ANNULATION', 'Annulation requise'), ('REGULARISATION', 'Régularisation requise'), ('AUCUNE', 'Aucune action requise')], default='NOTIFY_USER', max_length=20)),
                ('traitee', models.BooleanField(default=False, help_text='Le rejet a-t-il été traité/résolu?')),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('traite_par', models.CharField(blank=True, help_text='Utilisateur ayant traité le rejet', max_length=100)),
                ('notes_traitement', models.TextField(blank=True, help_text='Notes sur le traitement effectué')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes_rejetees', to='inventory.boutique')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes_rejetees', to='inventory.client')),
            ],
            options={
                'verbose_name': 'Vente rejetée',
                'verbose_name_plural': 'Ventes rejetées',
                'ordering': ['-date_tentative'],
                'indexes': [models.Index(fields=['boutique', 'date_tentative'], name='rejet_boutique_date_idx'), models.Index(fields=['raison_rejet'], name='rejet_raison_idx'), models.Index(fields=['traitee'], name='rejet_traitee_idx')],
            },
        ),
    ]
