# Generated by Django 5.2 on 2025-12-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_add_vente_rejetee'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='annulee_par',
            field=models.CharField(blank=True, help_text='Terminal ou utilisateur ayant annulé', max_length=100),
        ),
        migrations.AddField(
            model_name='vente',
            name='date_annulation',
            field=models.DateTimeField(blank=True, help_text="Date et heure de l'annulation", null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='est_annulee',
            field=models.BooleanField(default=False, help_text='La vente a-t-elle été annulée?'),
        ),
        migrations.AddField(
            model_name='vente',
            name='motif_annulation',
            field=models.TextField(blank=True, help_text="Raison de l'annulation"),
        ),
    ]
