# Generated by Django 5.2 on 2026-01-01 15:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_vente_annulee_par_vente_date_annulation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='est_depot',
            field=models.BooleanField(default=False, help_text='Est-ce un dépôt central de stockage?'),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='type_commerce',
            field=models.CharField(choices=[('DEPOT', 'Dépôt central'), ('PHARMACIE', 'Pharmacie'), ('ALIMENTATION', 'Alimentation générale'), ('SUPERMARCHE', 'Supermarché'), ('BOUTIQUE', 'Boutique générale'), ('KIOSQUE', 'Kiosque'), ('BAR', 'Bar/Café'), ('RESTAURANT', 'Restaurant / Fast-food'), ('HABILLEMENT', 'Habillement / Friperie'), ('COIFFURE_BEAUTE', 'Salon de coiffure / Beauté'), ('ELECTRONIQUE', 'Appareils électroniques / Accessoires'), ('TELEPHONIE_MOBILE', 'Téléphonie / Mobile Money'), ('QUINCAILLERIE', 'Quincaillerie'), ('SERVICES_BUREAU', 'Services bureautiques / Cybercafé'), ('AUTRE', 'Autre')], default='BOUTIQUE', max_length=50),
        ),
        migrations.CreateModel(
            name='TransfertStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('date_transfert', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('effectue_par', models.CharField(help_text='Utilisateur ayant effectué le transfert', max_length=100)),
                ('valide_par', models.CharField(blank=True, help_text='Utilisateur ayant validé le transfert', max_length=100)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('stock_depot_avant', models.IntegerField(blank=True, help_text='Stock du dépôt avant transfert', null=True)),
                ('stock_depot_apres', models.IntegerField(blank=True, help_text='Stock du dépôt après transfert', null=True)),
                ('stock_boutique_avant', models.IntegerField(blank=True, help_text='Stock de la boutique avant transfert', null=True)),
                ('stock_boutique_apres', models.IntegerField(blank=True, help_text='Stock de la boutique après transfert', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts', to='inventory.article')),
                ('boutique_destination', models.ForeignKey(help_text='Boutique de destination', on_delete=django.db.models.deletion.CASCADE, related_name='transferts_entrants', to='inventory.boutique')),
                ('depot_source', models.ForeignKey(help_text="Dépôt d'origine", on_delete=django.db.models.deletion.CASCADE, related_name='transferts_sortants', to='inventory.boutique')),
            ],
            options={
                'verbose_name': 'Transfert de stock',
                'verbose_name_plural': 'Transferts de stock',
                'ordering': ['-date_transfert'],
                'indexes': [models.Index(fields=['depot_source', 'date_transfert'], name='transfert_depot_date_idx'), models.Index(fields=['boutique_destination', 'date_transfert'], name='transfert_boutique_date_idx'), models.Index(fields=['statut'], name='transfert_statut_idx')],
            },
        ),
    ]
