# Generated by Django 5.2 on 2026-01-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_boutique_est_depot_alter_boutique_type_commerce_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('code', 'boutique')},
        ),
    ]
