# Generated by Django 5.2 on 2026-01-11 03:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_change_article_code_unique_per_boutique'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='prix_achat_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Prix d'achat en USD", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='prix_vente_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix de vente en USD', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='lignevente',
            name='devise',
            field=models.CharField(choices=[('CDF', 'Franc Congolais'), ('USD', 'Dollar US')], default='CDF', max_length=3),
        ),
        migrations.AddField(
            model_name='lignevente',
            name='prix_unitaire_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix unitaire en USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='devise',
            field=models.CharField(choices=[('CDF', 'Franc Congolais'), ('USD', 'Dollar US')], default='CDF', help_text='Devise utilisée pour cette vente', max_length=3),
        ),
        migrations.AddField(
            model_name='vente',
            name='montant_total_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant total en USD', max_digits=12, null=True),
        ),
    ]
