# Generated by Django 5.2 on 2026-01-11 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_add_usd_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='devise',
            field=models.CharField(choices=[('CDF', 'Franc Congolais'), ('USD', 'Dollar US')], default='CDF', help_text='Devise des prix de cet article', max_length=3),
        ),
        migrations.AlterField(
            model_name='article',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Prix d'achat dans la devise de l'article", max_digits=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='prix_achat_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Prix d'achat converti en USD (si devise=CDF)", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='prix_vente',
            field=models.DecimalField(decimal_places=2, help_text="Prix de vente dans la devise de l'article", max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='article',
            name='prix_vente_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix de vente converti en USD (si devise=CDF)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
