# Generated by Django 5.2 on 2026-01-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_add_devise_to_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='taux_dollar',
            field=models.DecimalField(decimal_places=2, default=2800, help_text='Taux de change: 1 USD = X CDF', max_digits=10),
        ),
    ]
