# Generated by Django 5.2 on 2026-01-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_add_taux_dollar'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercant',
            name='taux_dollar',
            field=models.DecimalField(decimal_places=2, default=2800, help_text='Taux de change: 1 USD = X CDF (appliqué à tous les points de vente)', max_digits=10),
        ),
    ]
