# Generated by Django 5.2 on 2026-01-12 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_add_taux_dollar_commercant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boutique',
            name='taux_dollar',
        ),
    ]
