# Generated by Django 5.2 on 2026-01-21 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_remove_taux_dollar_boutique'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('STOCK_AJOUT', 'Ajout de stock'), ('STOCK_TRANSFERT', 'Transfert de stock'), ('STOCK_AJUSTEMENT', 'Ajustement de stock')], default='STOCK_AJOUT', max_length=20)),
                ('titre', models.CharField(help_text='Titre court de la notification', max_length=200)),
                ('message', models.TextField(help_text='Message détaillé de la notification')),
                ('quantite_ajoutee', models.IntegerField(default=0, help_text='Quantité ajoutée au stock')),
                ('stock_actuel', models.IntegerField(default=0, help_text="Stock actuel après l'ajout")),
                ('lue', models.BooleanField(default=False, help_text='La notification a-t-elle été lue?')),
                ('date_lecture', models.DateTimeField(blank=True, help_text='Date et heure de lecture', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création de la notification')),
                ('donnees_supplementaires', models.JSONField(blank=True, help_text='Données supplémentaires (prix, catégorie, etc.)', null=True)),
                ('article', models.ForeignKey(blank=True, help_text='Article concerné', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='inventory.article')),
                ('boutique', models.ForeignKey(help_text='Boutique concernée par la notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='inventory.boutique')),
                ('client', models.ForeignKey(help_text='Client MAUI destinataire de la notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='inventory.client')),
                ('mouvement_stock', models.ForeignKey(blank=True, help_text='Mouvement de stock associé', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='inventory.mouvementstock')),
            ],
            options={
                'verbose_name': 'Notification de stock',
                'verbose_name_plural': 'Notifications de stock',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['client', 'lue', '-date_creation'], name='notif_client_lue_date_idx'), models.Index(fields=['boutique', '-date_creation'], name='notif_boutique_date_idx'), models.Index(fields=['lue', '-date_creation'], name='notif_lue_date_idx')],
            },
        ),
    ]
