# Generated by Django 5.2 on 2026-01-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_notificationstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationstock',
            name='quantite_mouvement',
            field=models.IntegerField(default=0, help_text='Quantité du mouvement (positif pour ajout, négatif pour retrait)'),
        ),
        migrations.AddField(
            model_name='notificationstock',
            name='stock_avant',
            field=models.IntegerField(default=0, help_text='Stock avant le mouvement'),
        ),
        migrations.AlterField(
            model_name='notificationstock',
            name='quantite_ajoutee',
            field=models.IntegerField(default=0, help_text='[DEPRECATED] Utiliser quantite_mouvement'),
        ),
        migrations.AlterField(
            model_name='notificationstock',
            name='stock_actuel',
            field=models.IntegerField(default=0, help_text='Stock actuel après le mouvement'),
        ),
        migrations.AlterField(
            model_name='notificationstock',
            name='type_notification',
            field=models.CharField(choices=[('STOCK_AJOUT', 'Ajout de stock'), ('STOCK_RETRAIT', 'Retrait de stock'), ('STOCK_TRANSFERT', 'Transfert de stock'), ('STOCK_AJUSTEMENT', 'Ajustement de stock'), ('AJUSTEMENT_PRIX', 'Ajustement de prix')], default='STOCK_AJOUT', max_length=20),
        ),
    ]
