# Generated by Django 5.2 on 2026-01-31 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_merge_0028_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilangeneral',
            name='boutique',
            field=models.ForeignKey(blank=True, help_text='Boutique spécifique (si bilan par boutique)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bilans', to='inventory.boutique'),
        ),
        migrations.AlterField(
            model_name='bilangeneral',
            name='commercant',
            field=models.ForeignKey(blank=True, help_text='Commerçant concerné (si bilan global)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bilans_generaux', to='inventory.commercant'),
        ),
        migrations.AlterUniqueTogether(
            name='indicateurperformance',
            unique_together={('nom', 'boutique', 'commercant')},
        ),
        migrations.AddIndex(
            model_name='bilangeneral',
            index=models.Index(fields=['commercant', 'periode', '-date_generation'], name='bilan_commercant_periode_idx'),
        ),
        migrations.AddIndex(
            model_name='bilangeneral',
            index=models.Index(fields=['boutique', '-date_generation'], name='bilan_boutique_date_idx'),
        ),
        migrations.AddIndex(
            model_name='bilangeneral',
            index=models.Index(fields=['statut', '-date_generation'], name='bilan_statut_date_idx'),
        ),
    ]
