# Generated by Django 5.2 on 2026-02-02 00:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_alter_bilangeneral_boutique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarianteArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_barre', models.CharField(help_text='Code-barres unique de cette variante', max_length=100)),
                ('nom_variante', models.CharField(help_text='Nom de la variante (couleur, taille, parfum, etc.)', max_length=100)),
                ('type_attribut', models.CharField(choices=[('COULEUR', 'Couleur'), ('TAILLE', 'Taille'), ('PARFUM', 'Parfum'), ('POIDS', 'Poids'), ('VOLUME', 'Volume'), ('MODELE', 'Modèle'), ('AUTRE', 'Autre')], default='AUTRE', help_text="Type d'attribut de cette variante", max_length=20)),
                ('quantite_stock', models.IntegerField(default=0, help_text='Stock disponible pour cette variante', validators=[django.core.validators.MinValueValidator(0)])),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='variantes/')),
                ('article_parent', models.ForeignKey(help_text='Article parent dont cette variante hérite le prix', on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='inventory.article')),
            ],
            options={
                'verbose_name': "Variante d'article",
                'verbose_name_plural': "Variantes d'articles",
                'ordering': ['article_parent__nom', 'nom_variante'],
            },
        ),
        migrations.AddField(
            model_name='lignevente',
            name='variante',
            field=models.ForeignKey(blank=True, help_text='Variante spécifique vendue (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_vente', to='inventory.variantearticle'),
        ),
        migrations.AddConstraint(
            model_name='variantearticle',
            constraint=models.UniqueConstraint(fields=('code_barre',), name='unique_code_barre_variante'),
        ),
        migrations.AlterUniqueTogether(
            name='variantearticle',
            unique_together={('code_barre', 'article_parent')},
        ),
    ]
