# Generated by Django 5.2 on 2026-02-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_add_variante_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_expiration',
            field=models.DateField(blank=True, help_text="Date d'expiration du produit", null=True),
        ),
    ]
