# Generated by Django 5.2 on 2026-02-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_add_date_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignevente',
            name='est_negocie',
            field=models.BooleanField(default=False, help_text='Prix négocié avec le client'),
        ),
        migrations.AddField(
            model_name='lignevente',
            name='prix_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix original avant négociation', max_digits=10, null=True),
        ),
    ]
