# Generated by Django 5.2 on 2026-02-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_add_prix_negocie_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lignevente',
            index=models.Index(fields=['est_negocie'], name='idx_ligne_negocie'),
        ),
        migrations.AddIndex(
            model_name='lignevente',
            index=models.Index(fields=['vente', 'est_negocie'], name='idx_ligne_vente_nego'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['date_vente'], name='idx_vente_date'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['client_maui', 'date_vente'], name='idx_vente_client_date'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['paye', 'est_annulee'], name='idx_vente_statut'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['boutique', 'date_vente'], name='idx_vente_boutique_date'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['devise'], name='idx_vente_devise'),
        ),
    ]
