# Generated by Django 5.2 on 2026-02-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_add_performance_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['boutique', 'est_actif'], name='idx_article_boutique_actif'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['boutique', 'est_actif', 'nom'], name='idx_article_boutique_nom'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['quantite_stock'], name='idx_article_stock'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['date_expiration'], name='idx_article_expiration'),
        ),
    ]
