# Generated by Django 5.2 on 2026-02-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_add_article_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignevente',
            name='motif_reduction',
            field=models.CharField(blank=True, default='', help_text='Motif/justification de la réduction accordée', max_length=255),
        ),
    ]
