# Generated by Django 5.2 on 2026-02-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_add_motif_reduction_to_lignevente'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_envoi',
            field=models.DateTimeField(blank=True, help_text="Date d'envoi pour validation client", null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='date_validation',
            field=models.DateTimeField(blank=True, help_text='Date de validation par le client MAUI', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='est_valide_client',
            field=models.BooleanField(default=False, help_text="L'article a été validé par le client MAUI (quantité vérifiée)"),
        ),
        migrations.AddField(
            model_name='article',
            name='quantite_envoyee',
            field=models.IntegerField(default=0, help_text='Quantité envoyée depuis Django en attente de validation'),
        ),
    ]
