# Generated by Django 5.2 on 2026-02-15 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_set_existing_articles_validated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du fournisseur', max_length=200)),
                ('contact', models.CharField(blank=True, help_text='Téléphone ou email', max_length=100)),
                ('adresse', models.TextField(blank=True, help_text='Adresse du fournisseur')),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseurs', to='inventory.commercant')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
                'unique_together': {('nom', 'commercant')},
            },
        ),
        migrations.CreateModel(
            name='FactureApprovisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(help_text='Numéro de facture fournisseur', max_length=100)),
                ('fournisseur_nom', models.CharField(blank=True, help_text='Nom du fournisseur (si pas dans la liste)', max_length=200)),
                ('date_facture', models.DateField(help_text='Date de la facture')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, help_text='Montant total de la facture', max_digits=15)),
                ('devise', models.CharField(choices=[('CDF', 'Franc Congolais'), ('USD', 'Dollar US')], default='CDF', max_length=3)),
                ('notes', models.TextField(blank=True, help_text='Notes ou commentaires')),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_approvisionnement', to='inventory.boutique')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='inventory.fournisseur')),
            ],
            options={
                'verbose_name': "Facture d'approvisionnement",
                'verbose_name_plural': "Factures d'approvisionnement",
                'ordering': ['-date_facture', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneApprovisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_quantite', models.CharField(choices=[('UNITE', 'Unités'), ('CARTON', 'Cartons')], default='UNITE', max_length=10)),
                ('nombre_cartons', models.IntegerField(default=0, help_text='Nombre de cartons')),
                ('pieces_par_carton', models.IntegerField(default=1, help_text='Nombre de pièces par carton')),
                ('quantite_unites', models.IntegerField(help_text='Quantité totale en unités')),
                ('prix_achat_carton', models.DecimalField(decimal_places=2, default=0, help_text="Prix d'achat par carton", max_digits=12)),
                ('prix_achat_unitaire', models.DecimalField(decimal_places=2, help_text="Prix d'achat unitaire calculé", max_digits=12)),
                ('prix_achat_total', models.DecimalField(decimal_places=2, help_text='Prix total de la ligne', max_digits=15)),
                ('prix_vente_unitaire', models.DecimalField(decimal_places=2, default=0, help_text='Prix de vente unitaire', max_digits=12)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_approvisionnement', to='inventory.article')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.categorie')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='inventory.factureapprovisionnement')),
            ],
            options={
                'verbose_name': "Ligne d'approvisionnement",
                'verbose_name_plural': "Lignes d'approvisionnement",
                'ordering': ['date_creation'],
            },
        ),
        migrations.AddIndex(
            model_name='factureapprovisionnement',
            index=models.Index(fields=['depot', '-date_facture'], name='facture_depot_date_idx'),
        ),
        migrations.AddIndex(
            model_name='factureapprovisionnement',
            index=models.Index(fields=['numero_facture'], name='facture_numero_idx'),
        ),
    ]
