# Generated by Django 5.2 on 2026-02-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_add_fournisseur_facture_approvisionnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='taux_dollar',
            field=models.DecimalField(decimal_places=2, default=2800, help_text='Taux de change USD vers CDF pour conversion des factures', max_digits=10),
        ),
    ]
