# Generated by Django 5.2 on 2026-02-16 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_add_taux_dollar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text="Référence unique de l'inventaire", max_length=50, unique=True)),
                ('date_inventaire', models.DateField(help_text="Date de l'inventaire")),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('REGULARISE', 'Régularisé'), ('ANNULE', 'Annulé')], default='EN_COURS', max_length=20)),
                ('nb_articles', models.IntegerField(default=0)),
                ('nb_ecarts', models.IntegerField(default=0)),
                ('valeur_ecart_positif', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valeur_ecart_negatif', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('date_regularisation', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaires_crees', to=settings.AUTH_USER_MODEL)),
                ('depot', models.ForeignKey(limit_choices_to={'est_depot': True}, on_delete=django.db.models.deletion.CASCADE, related_name='inventaires', to='inventory.boutique')),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_theorique', models.IntegerField(help_text="Stock système au moment de l'inventaire")),
                ('stock_physique', models.IntegerField(blank=True, help_text='Stock compté physiquement', null=True)),
                ('ecart', models.IntegerField(default=0, help_text='Écart (physique - théorique)')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, help_text="Prix d'achat unitaire", max_digits=12)),
                ('valeur_ecart', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('est_regularise', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True, help_text="Commentaire ou justification de l'écart")),
                ('date_saisie', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_inventaire', to='inventory.article')),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='inventory.inventaire')),
            ],
            options={
                'verbose_name': "Ligne d'inventaire",
                'verbose_name_plural': "Lignes d'inventaire",
                'ordering': ['article__nom'],
                'unique_together': {('inventaire', 'article')},
            },
        ),
    ]
