# Generated by Django 5.2 on 2026-02-19 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_rename_depot_to_boutique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaire',
            name='boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaires', to='inventory.boutique'),
        ),
        migrations.AlterUniqueTogether(
            name='factureapprovisionnement',
            unique_together={('numero_facture', 'depot')},
        ),
    ]
