# Generated by Django 5.2 on 2026-02-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_facture_numero_unique_per_depot'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfertstock',
            name='reference_lot',
            field=models.CharField(blank=True, db_index=True, help_text='Référence de lot pour regrouper les transferts multiples', max_length=50),
        ),
    ]
