# Generated by Django 5.2 on 2026-02-23 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_transfert_reference_lot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErreurTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_erreur', models.CharField(choices=[('VENTE', 'Erreur de vente'), ('PAIEMENT', 'Erreur de paiement'), ('STOCK', 'Erreur de stock'), ('SYNC', 'Erreur de synchronisation'), ('API', 'Erreur API'), ('AUTRE', 'Autre erreur')], default='VENTE', max_length=20)),
                ('gravite', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Avertissement'), ('ERROR', 'Erreur'), ('CRITICAL', 'Critique')], default='ERROR', max_length=20)),
                ('message', models.TextField(help_text="Message d'erreur principal")),
                ('details', models.TextField(blank=True, help_text='Détails techniques (traceback, etc.)')),
                ('donnees_contexte', models.JSONField(blank=True, default=dict, help_text='Données de contexte JSON (panier, articles, etc.)')),
                ('url_requete', models.CharField(blank=True, max_length=500)),
                ('methode_requete', models.CharField(blank=True, max_length=10)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('est_resolu', models.BooleanField(default=False)),
                ('note_resolution', models.TextField(blank=True, help_text='Notes de résolution')),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('boutique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erreurs_transactions', to='inventory.boutique')),
                ('client_maui', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erreurs_transactions', to='inventory.client')),
                ('commercant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erreurs_transactions', to='inventory.commercant')),
                ('resolu_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erreurs_resolues', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erreurs_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Erreur de transaction',
                'verbose_name_plural': 'Erreurs de transactions',
                'ordering': ['-date_creation'],
            },
        ),
    ]
