# Generated by Django 5.2 on 2026-02-27 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0046_erreur_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutique',
            name='type_commerce',
            field=models.CharField(choices=[('GENERAL', 'Commerce Général'), ('MOBILE_MONEY', 'Mobile Money'), ('DEPOT', 'Dépôt central'), ('PHARMACIE', 'Pharmacie'), ('ALIMENTATION', 'Alimentation générale'), ('SUPERMARCHE', 'Supermarché'), ('BOUTIQUE', 'Boutique générale'), ('KIOSQUE', 'Kiosque'), ('BAR', 'Bar/Café'), ('RESTAURANT', 'Restaurant / Fast-food'), ('HABILLEMENT', 'Habillement / Friperie'), ('COIFFURE_BEAUTE', 'Salon de coiffure / Beauté'), ('ELECTRONIQUE', 'Appareils électroniques / Accessoires'), ('TELEPHONIE_MOBILE', 'Téléphonie / Mobile Money'), ('QUINCAILLERIE', 'Quincaillerie'), ('SERVICES_BUREAU', 'Services bureautiques / Cybercafé'), ('AUTRE', 'Autre')], default='GENERAL', max_length=50),
        ),
        migrations.CreateModel(
            name='TransactionMobileMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('DEPOT', 'Dépôt'), ('RETRAIT', 'Retrait'), ('TRANSFERT', 'Transfert'), ('PAIEMENT', 'Paiement facture')], max_length=20)),
                ('operateur', models.CharField(choices=[('AIRTEL', 'Airtel Money'), ('VODACOM', 'M-Pesa (Vodacom)'), ('ORANGE', 'Orange Money'), ('AFRICELL', 'Africell Money')], max_length=20)),
                ('numero_telephone_client', models.CharField(help_text='Numéro de téléphone du client', max_length=20)),
                ('nom_client', models.CharField(blank=True, help_text='Nom du client (optionnel)', max_length=100)),
                ('numero_destinataire', models.CharField(blank=True, help_text='Numéro du destinataire (pour transferts)', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant de la transaction', max_digits=15)),
                ('commission', models.DecimalField(decimal_places=2, default=0, help_text='Commission perçue', max_digits=10)),
                ('montant_net', models.DecimalField(decimal_places=2, help_text='Montant net (après commission)', max_digits=15)),
                ('reference_operateur', models.CharField(blank=True, help_text="Code de confirmation de l'opérateur", max_length=100)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé'), ('ANNULE', 'Annulé'), ('ECHOUE', 'Échoué')], default='EN_ATTENTE', max_length=20)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_mobile_money', to='inventory.boutique')),
                ('effectue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction Mobile Money',
                'verbose_name_plural': 'Transactions Mobile Money',
                'ordering': ['-date_transaction'],
            },
        ),
    ]
