# Generated by Django 5.2 on 2026-02-27 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0047_add_mobile_money'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmobilemoney',
            name='operateur',
            field=models.CharField(choices=[('AIRTEL', 'Airtel Money'), ('VODACOM', 'M-Pesa (Vodacom)'), ('ORANGE', 'Orange Money'), ('AFRICELL', 'Africell Money'), ('AFRIMONEY', 'Afrimoney')], max_length=20),
        ),
        migrations.CreateModel(
            name='ApprovisionnementCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(choices=[('AIRTEL', 'Airtel'), ('VODACOM', 'Vodacom'), ('ORANGE', 'Orange'), ('AFRICELL', 'Africell'), ('AFRIMONEY', 'Afrimoney')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant approvisionné', max_digits=15)),
                ('cout_achat', models.DecimalField(decimal_places=2, help_text="Coût d'achat du crédit", max_digits=15)),
                ('fournisseur', models.CharField(blank=True, help_text='Nom du fournisseur', max_length=100)),
                ('reference', models.CharField(blank=True, help_text='Référence de la transaction', max_length=100)),
                ('date_approvisionnement', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvisionnements_credit', to='inventory.boutique')),
                ('effectue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approvisionnement crédit',
                'verbose_name_plural': 'Approvisionnements crédit',
                'ordering': ['-date_approvisionnement'],
            },
        ),
        migrations.CreateModel(
            name='VenteCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vente', models.CharField(choices=[('DETAIL', 'Détail'), ('GROS', 'Gros')], default='DETAIL', max_length=10)),
                ('operateur', models.CharField(choices=[('AIRTEL', 'Airtel'), ('VODACOM', 'Vodacom'), ('ORANGE', 'Orange'), ('AFRICELL', 'Africell'), ('AFRIMONEY', 'Afrimoney')], max_length=20)),
                ('numero_telephone_client', models.CharField(blank=True, help_text='Numéro du client (pour gros)', max_length=20)),
                ('nom_client', models.CharField(blank=True, help_text='Nom du client (pour gros)', max_length=100)),
                ('montant_achat', models.DecimalField(decimal_places=2, help_text="Montant d'achat du crédit", max_digits=15)),
                ('montant_vente', models.DecimalField(decimal_places=2, help_text='Montant de vente au client', max_digits=15)),
                ('benefice', models.DecimalField(decimal_places=2, default=0, help_text='Bénéfice réalisé', max_digits=10)),
                ('quantite', models.IntegerField(default=1, help_text="Quantité d'unités de crédit")),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes_credit', to='inventory.boutique')),
                ('effectue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vente de crédit',
                'verbose_name_plural': 'Ventes de crédit',
                'ordering': ['-date_vente'],
            },
        ),
        migrations.CreateModel(
            name='StockCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(choices=[('AIRTEL', 'Airtel'), ('VODACOM', 'Vodacom'), ('ORANGE', 'Orange'), ('AFRICELL', 'Africell'), ('AFRIMONEY', 'Afrimoney')], max_length=20)),
                ('stock_actuel', models.DecimalField(decimal_places=2, default=0, help_text='Stock de crédit disponible', max_digits=15)),
                ('seuil_alerte', models.DecimalField(decimal_places=2, default=50000, help_text="Seuil d'alerte stock bas", max_digits=15)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_credit', to='inventory.boutique')),
            ],
            options={
                'verbose_name': 'Stock de crédit',
                'verbose_name_plural': 'Stocks de crédit',
                'unique_together': {('boutique', 'operateur')},
            },
        ),
    ]
