# Generated by Django 5.2 on 2026-02-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0048_add_vente_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvisionnementcredit',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='stockcredit',
            name='stock_actuel',
        ),
        migrations.RemoveField(
            model_name='ventecredit',
            name='montant_achat',
        ),
        migrations.RemoveField(
            model_name='ventecredit',
            name='montant_vente',
        ),
        migrations.RemoveField(
            model_name='ventecredit',
            name='quantite',
        ),
        migrations.AddField(
            model_name='approvisionnementcredit',
            name='unites',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Unités envoyées par flash (en FC)', max_digits=15),
        ),
        migrations.AddField(
            model_name='stockcredit',
            name='cout_total_achats',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Coût total des achats', max_digits=15),
        ),
        migrations.AddField(
            model_name='stockcredit',
            name='unites_disponibles',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Unités de crédit disponibles (en FC)', max_digits=15),
        ),
        migrations.AddField(
            model_name='ventecredit',
            name='montant_recu',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant reçu du client', max_digits=15),
        ),
        migrations.AddField(
            model_name='ventecredit',
            name='unites_vendues',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Unités de crédit vendues (en FC)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='approvisionnementcredit',
            name='cout_achat',
            field=models.DecimalField(decimal_places=2, help_text="Coût d'achat des unités", max_digits=15),
        ),
        migrations.AlterField(
            model_name='approvisionnementcredit',
            name='fournisseur',
            field=models.CharField(blank=True, help_text='Source du flash', max_length=100),
        ),
    ]
