# Generated by Django 5.2 on 2026-03-02 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_remove_approvisionnementcredit_montant_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='variantearticle',
            name='unique_code_barre_variante',
        ),
    ]
