# Generated by Django 5.2 on 2026-03-05 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_remove_global_unique_variante_code_barre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('STOCK_INSUFFISANT', 'Stock insuffisant'), ('STOCK_NEGATIF', 'Stock devenu négatif'), ('ECART_STOCK', 'Écart de stock détecté')], default='STOCK_INSUFFISANT', max_length=30)),
                ('quantite_vendue', models.PositiveIntegerField(help_text='Quantité vendue par le client')),
                ('stock_serveur_avant', models.IntegerField(help_text='Stock serveur avant la vente')),
                ('stock_serveur_apres', models.IntegerField(help_text='Stock serveur après la vente (peut être négatif)')),
                ('ecart', models.IntegerField(help_text='Écart de stock (négatif = manque)')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de régularisation'), ('REGULARISE', 'Régularisé'), ('IGNORE', 'Ignoré')], default='EN_ATTENTE', max_length=20)),
                ('date_regularisation', models.DateTimeField(blank=True, null=True)),
                ('notes_regularisation', models.TextField(blank=True, help_text='Notes sur la régularisation effectuée')),
                ('action_suggeree', models.TextField(blank=True, help_text='Action suggérée pour régulariser')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('numero_facture', models.CharField(blank=True, max_length=100)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_stock', to='inventory.article')),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_stock', to='inventory.boutique')),
                ('regularise_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_regularisees', to=settings.AUTH_USER_MODEL)),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_stock', to='inventory.client')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_stock', to='inventory.variantearticle')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_stock', to='inventory.vente')),
            ],
            options={
                'verbose_name': 'Alerte stock',
                'verbose_name_plural': 'Alertes stock',
                'ordering': ['-date_creation'],
            },
        ),
    ]
