# Generated by Django 5.2 on 2026-03-05 22:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0051_alertestock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Prix d'achat dans la devise de l'article", max_digits=15),
        ),
        migrations.AlterField(
            model_name='article',
            name='prix_achat_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Prix d'achat converti en USD (si devise=CDF)", max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='prix_vente',
            field=models.DecimalField(decimal_places=2, help_text="Prix de vente dans la devise de l'article", max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='article',
            name='prix_vente_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix de vente converti en USD (si devise=CDF)', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='prix_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix original avant négociation', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='prix_unitaire_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix unitaire en USD', max_digits=15, null=True),
        ),
    ]
