# Generated by Django 5.2 on 2026-03-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0052_increase_price_field_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneinventaire',
            name='assigne_a',
            field=models.CharField(blank=True, help_text="Nom de l'employé assigné à compter cet article", max_length=100),
        ),
    ]
