# Generated by Django 5.2 on 2026-03-13 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0053_ligneinventaire_assigne_a'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneinventaire',
            name='date_modification',
            field=models.DateTimeField(blank=True, help_text='Dernière modification du stock physique', null=True),
        ),
        migrations.AddField(
            model_name='ligneinventaire',
            name='saisi_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a saisi le stock physique', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_inventaire_saisies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('INVENTAIRE', 'Inventaire uniquement'), ('VENDEUR', 'Vendeur'), ('GESTIONNAIRE', 'Gestionnaire')], default='INVENTAIRE', help_text='Rôle et permissions du collaborateur', max_length=20)),
                ('est_actif', models.BooleanField(default=True, help_text='Le collaborateur peut-il se connecter?')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('code_pin', models.CharField(blank=True, help_text='Code PIN à 4-6 chiffres pour accès rapide', max_length=6)),
                ('boutiques_autorisees', models.ManyToManyField(blank=True, help_text='Boutiques auxquelles ce collaborateur a accès', related_name='collaborateurs_autorises', to='inventory.boutique')),
                ('commercant', models.ForeignKey(help_text='Commerçant pour lequel travaille ce collaborateur', on_delete=django.db.models.deletion.CASCADE, related_name='collaborateurs', to='inventory.commercant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_collaborateur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collaborateur',
                'verbose_name_plural': 'Collaborateurs',
                'ordering': ['nom_complet'],
            },
        ),
    ]
