# Generated by Django 5.2 on 2026-03-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0054_ligneinventaire_date_modification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Dernière modification pour sync incrémentale'),
        ),
        migrations.AddField(
            model_name='article',
            name='version',
            field=models.IntegerField(default=1, help_text='Version pour sync optimisée'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Dernière modification pour sync incrémentale'),
        ),
        migrations.AddField(
            model_name='variantearticle',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Dernière modification pour sync incrémentale'),
        ),
    ]
