# Generated by Django 5.0.14 on 2026-03-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0055_article_last_updated_article_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='quantite_attribuee',
            field=models.IntegerField(default=0, help_text='Référence quantité attribuée (configurable indépendamment par article)'),
        ),
    ]
