# Generated by Django 5.0.14 on 2026-03-23 20:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0056_quantite_attribuee_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAcompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=25)),
                ('adresse', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients_credit', to='inventory.boutique')),
            ],
            options={
                'verbose_name': 'Client Acompte',
                'verbose_name_plural': 'Clients Acompte',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='VenteAcompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=25, unique=True)),
                ('article_nom', models.CharField(help_text="Nom snapshot de l'article", max_length=200)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(1)])),
                ('seuil_retrait', models.DecimalField(decimal_places=2, help_text="Montant minimum à payer pour autoriser le retrait de l'article", max_digits=15)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('SOLDE', 'Soldé'), ('ANNULE', 'Annulé')], default='EN_COURS', max_length=20)),
                ('article_recupere', models.BooleanField(default=False)),
                ('date_retrait', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_acompte', to='inventory.article')),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes_acompte', to='inventory.boutique')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='inventory.clientacompte')),
            ],
            options={
                'verbose_name': 'Vente Acompte',
                'verbose_name_plural': 'Ventes Acompte',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PaiementAcompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_recu', models.CharField(editable=False, max_length=25, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(1)])),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('recu_par', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='inventory.venteacompte')),
            ],
            options={
                'verbose_name': 'Paiement Acompte',
                'verbose_name_plural': 'Paiements Acompte',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.AddIndex(
            model_name='clientacompte',
            index=models.Index(fields=['boutique'], name='idx_clientacompte_boutique'),
        ),
        migrations.AddIndex(
            model_name='venteacompte',
            index=models.Index(fields=['boutique', 'statut'], name='idx_venteacompte_statut'),
        ),
    ]
