# Generated by Django 5.0.14 on 2026-03-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0057_add_acompte_payment_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date réception par Django (heure serveur)', null=True),
        ),
    ]
