# Generated by Django 5.2 on 2026-05-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0059_add_journal_valeur_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalvaleurstock',
            name='valeur_stock_reel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valeur réelle du stock = SUM(quantite_stock * prix_achat) des articles de la boutique', max_digits=18),
        ),
    ]
