# Generated by Django 5.2 on 2026-05-09 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0060_add_valeur_stock_reel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueSaisieInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_physique_saisi', models.IntegerField(help_text='Quantité saisie')),
                ('stock_theorique_au_moment', models.IntegerField(help_text='Stock système au moment de la saisie')),
                ('ecart_au_moment', models.IntegerField(default=0, help_text='Écart calculé au moment de la saisie')),
                ('nom_saisi_par', models.CharField(blank=True, help_text='Nom affiché du saisisseur', max_length=150)),
                ('commentaire', models.TextField(blank=True)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_saisies_inventaire', to='inventory.article')),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_saisies', to='inventory.inventaire')),
                ('ligne_inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_saisies', to='inventory.ligneinventaire')),
                ('saisi_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_saisies_inventaire', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique saisie inventaire',
                'verbose_name_plural': 'Historiques saisies inventaire',
                'ordering': ['-date_saisie'],
                'indexes': [models.Index(fields=['inventaire', 'article', '-date_saisie'], name='inventory_h_inventa_484416_idx')],
            },
        ),
    ]
