# Generated by Django 4.2.7 on 2026-06-23 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0061_add_historique_saisie_inventaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelechargementRapportMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField()),
                ('mois', models.PositiveIntegerField()),
                ('date_telechargement', models.DateTimeField(auto_now_add=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telechargements_rapport', to='inventory.boutique')),
                ('telecharge_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Téléchargement rapport mensuel',
                'verbose_name_plural': 'Téléchargements rapports mensuels',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('boutique', 'annee', 'mois')},
            },
        ),
    ]
