# Generated by Django 5.0.9 on 2026-08-15 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0063_fix_inventaire_ecart_prix_unitaire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalvaleurstock',
            name='valeur_stock_reel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valeur réelle du stock = SUM(quantite_stock * prix_vente) des articles de la boutique (valeur commerciale confiée au gérant)', max_digits=18),
        ),
        migrations.AlterField(
            model_name='journalvaleurstock',
            name='valeur_ventes',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valeur (au prix de vente) des articles vendus', max_digits=18),
        ),
        migrations.CreateModel(
            name='DemandeResetPdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField(blank=True, help_text='Motif de la demande (optionnel)')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDEE', 'Validée et exécutée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=20)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('reponse_admin', models.TextField(blank=True, help_text="Commentaire de l'administrateur (validation ou refus)")),
                ('resultat', models.TextField(blank=True, help_text='Journal des actions exécutées lors de la réinitialisation')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('boutique', models.ForeignKey(help_text='Boutique du point de vente', on_delete=django.db.models.deletion.CASCADE, related_name='demandes_reset', to='inventory.boutique')),
                ('demandeur', models.ForeignKey(help_text='Commerçant ou collaborateur ayant demandé la réinitialisation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_reset_effectuees', to=settings.AUTH_USER_MODEL)),
                ('terminal', models.ForeignKey(help_text='Point de vente (terminal MAUI) concerné', on_delete=django.db.models.deletion.CASCADE, related_name='demandes_reset', to='inventory.client')),
                ('traite_par', models.ForeignKey(blank=True, help_text='Administrateur ayant traité la demande', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_reset_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de réinitialisation PDV',
                'verbose_name_plural': 'Demandes de réinitialisation PDV',
                'ordering': ['-date_demande'],
            },
        ),
    ]
