# Generated by Django 5.0.9 on 2026-08-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0064_alter_journalvaleurstock_valeur_stock_reel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanderesetpdv',
            name='type_reset',
            field=models.CharField(choices=[('MAUI', 'Re-validation terminal MAUI'), ('SERVEUR', 'Réinitialisation serveur complète (destructif)')], default='MAUI', help_text='MAUI = re-validation des articles ; SERVEUR = remise à zéro des données côté Django', max_length=20),
        ),
    ]
