# Generated by Django 5.0.9 on 2026-08-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0065_demanderesetpdv_type_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fcm_token',
            field=models.TextField(blank=True, default='', help_text='Jeton FCM du terminal pour les notifications push'),
        ),
    ]
