# Generated by Django 5.2 on 2026-08-26 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0066_client_fcm_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre principal de la bannière', max_length=200)),
                ('sous_titre', models.CharField(blank=True, help_text='Texte secondaire optionnel', max_length=300)),
                ('image', models.ImageField(blank=True, help_text='Image de la bannière (optionnel)', null=True, upload_to='banners/')),
                ('couleur_fond', models.CharField(default='#1565C0', help_text='Couleur de fond hex (ex: #1565C0)', max_length=7)),
                ('texte_bouton', models.CharField(blank=True, help_text="Texte du bouton d'action (optionnel)", max_length=50)),
                ('action_type', models.CharField(choices=[('NONE', 'Aucune'), ('URL', 'Ouvrir URL'), ('SYNC', 'Synchroniser')], default='NONE', max_length=20)),
                ('action_cible', models.CharField(blank=True, help_text="URL ou paramètre de l'action", max_length=500)),
                ('est_active', models.BooleanField(default=True)),
                ('priorite', models.IntegerField(default=0, help_text='Plus grand = affiché en premier')),
                ('date_debut', models.DateTimeField(blank=True, help_text="Date de début d'affichage (vide = immédiat)", null=True)),
                ('date_fin', models.DateTimeField(blank=True, help_text="Date de fin d'affichage (vide = pas de limite)", null=True)),
                ('creee_le', models.DateTimeField(auto_now_add=True)),
                ('modifiee_le', models.DateTimeField(auto_now=True)),
                ('boutique', models.ForeignKey(blank=True, help_text='Null = toutes les boutiques', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.boutique')),
            ],
            options={
                'verbose_name': 'Bannière publicitaire',
                'verbose_name_plural': 'Bannières publicitaires',
                'ordering': ['-priorite', '-creee_le'],
            },
        ),
    ]
