# Generated by Django 5.2 on 2026-08-27 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0067_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre du message', max_length=200)),
                ('contenu', models.TextField(help_text='Contenu détaillé du message')),
                ('type_message', models.CharField(choices=[('PAIEMENT', 'Paiement'), ('INFO', 'Information'), ('ALERTE', 'Alerte'), ('MAINTENANCE', 'Maintenance')], default='INFO', help_text='Type de message (détermine la couleur)', max_length=20)),
                ('est_lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('commercant', models.ForeignKey(blank=True, help_text='Null = tous les commerçants', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.commercant')),
            ],
            options={
                'verbose_name': 'Message commerçant',
                'verbose_name_plural': 'Messages commerçants',
                'ordering': ['-date_creation'],
            },
        ),
    ]
