# Generated by Django 5.2.1 on 2026-09-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0070_normalize_point_vente_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pieces_par_carton',
            field=models.PositiveIntegerField(default=1, help_text='Nombre de pièces par carton (auto-rempli à la saisie facture)'),
        ),
    ]
