# Generated by Django 5.2.1 on 2026-09-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0071_article_pieces_par_carton'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalvaleurstock',
            name='montant_reductions',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total des réductions accordées sur les ventes du jour ((prix original − prix négocié) × quantité, CDF)', max_digits=18),
        ),
    ]
