# Generated by Django 5.2 on 2026-09-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0072_journalvaleurstock_montant_reductions'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlenegocie',
            name='article_nom',
            field=models.CharField(blank=True, help_text='Nom libre envoye par le terminal', max_length=200),
        ),
        migrations.AddField(
            model_name='articlenegocie',
            name='montant_reduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='articlenegocie',
            name='pourcentage_reduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='articlenegocie',
            name='prix_original',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='articlenegocie',
            name='source',
            field=models.CharField(default='CAISSE', help_text='CAISSE = negociation caisse, MANUEL = saisie back-office, ANNULATION = reduction ou vente annulee', max_length=20),
        ),
    ]
