# Generated by Django 5.2 on 2026-09-29 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0073_articlenegocie_article_nom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeCloture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code à saisir sur le terminal', max_length=20)),
                ('date_jour', models.DateField(help_text="Jour d'application du code (jour de la clôture)")),
                ('actif', models.BooleanField(default=True, help_text='Seul le dernier code actif est accepté')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('boutique', models.ForeignKey(help_text='Boutique concernée par ce code', on_delete=django.db.models.deletion.CASCADE, related_name='codes_cloture', to='inventory.boutique')),
                ('genere_par', models.ForeignKey(blank=True, help_text='Commerçant ayant généré le code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes_cloture_generes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code de clôture',
                'verbose_name_plural': 'Codes de clôture',
                'ordering': ['-date_generation'],
                'indexes': [models.Index(fields=['boutique', 'date_jour', 'actif'], name='inventory_c_boutiqu_70406c_idx')],
            },
        ),
    ]
