# Generated by Django 5.2 on 2026-10-03 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0074_code_cloture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClotureJournee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_jour', models.DateField(help_text='Jour de la clôture')),
                ('terminal_serial', models.CharField(blank=True, default='', help_text='Terminal ayant clôturé', max_length=100)),
                ('statut', models.CharField(choices=[('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée')], default='VALIDEE', max_length=10)),
                ('nombre_ventes', models.IntegerField(default=0)),
                ('total_ventes', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('date_annulation', models.DateTimeField(blank=True, null=True)),
                ('annulee_par', models.ForeignKey(blank=True, help_text='Commerçant ayant annulé la clôture', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clotures_journee_annulees', to=settings.AUTH_USER_MODEL)),
                ('boutique', models.ForeignKey(help_text='Boutique concernée par la clôture', on_delete=django.db.models.deletion.CASCADE, related_name='clotures_journee', to='inventory.boutique')),
            ],
            options={
                'verbose_name': 'Clôture de journée',
                'verbose_name_plural': 'Clôtures de journée',
                'ordering': ['-date_jour', '-date_cloture'],
                'indexes': [models.Index(fields=['boutique', 'date_jour', 'statut'], name='inventory_c_boutiqu_f6de79_idx')],
            },
        ),
    ]
