# Generated by Django 5.2 on 2026-10-04 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0075_cloturejournee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lignevente',
            name='annulee_par',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lignevente',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lignevente',
            name='est_annulee',
            field=models.BooleanField(default=False, help_text='Ligne annulée (article retiré de la facture)'),
        ),
        migrations.AddField(
            model_name='lignevente',
            name='motif_annulation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='DemandeAnnulationVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_demande', models.CharField(choices=[('FACTURE', 'Facture entière'), ('LIGNE', 'Un article de la facture')], default='FACTURE', max_length=10)),
                ('numero_facture', models.CharField(db_index=True, max_length=50)),
                ('article_nom', models.CharField(blank=True, default='', max_length=200)),
                ('motif', models.TextField(blank=True, help_text='Motif saisi par le terminal MAUI')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente du commerçant'), ('ACCEPTEE', 'Acceptée — prolongation accordée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=20)),
                ('delai_accorde_minutes', models.PositiveIntegerField(default=0)),
                ('expire_le', models.DateTimeField(blank=True, help_text='Fin de validité de la prolongation accordée', null=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('reponse', models.CharField(blank=True, default='', max_length=255)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_annulation', to='inventory.boutique')),
                ('ligne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_annulation', to='inventory.lignevente')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_annulation', to='inventory.client')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_annulation_traitees', to=settings.AUTH_USER_MODEL)),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_annulation', to='inventory.vente')),
            ],
            options={
                'verbose_name': "Demande d'annulation de vente",
                'verbose_name_plural': "Demandes d'annulation de ventes",
                'ordering': ['-date_demande'],
                'indexes': [models.Index(fields=['boutique', 'statut'], name='idx_demande_annul_bs')],
            },
        ),
    ]
