# Generated by Django 5.2 on 2026-10-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0076_lignevente_annulee_par_lignevente_date_annulation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignevente',
            name='motif_annulation_code',
            field=models.CharField(blank=True, choices=[('ERREUR_COMMANDE', 'Achat par erreur du client'), ('ARTICLE_DEFECTUEUX', 'Article défectueux')], default='', help_text='ERREUR_COMMANDE (retour en stock) ou ARTICLE_DEFECTUEUX (sortie, pas de retour)', max_length=32),
        ),
        migrations.AddField(
            model_name='vente',
            name='motif_annulation_code',
            field=models.CharField(blank=True, choices=[('ERREUR_COMMANDE', 'Achat par erreur du client'), ('ARTICLE_DEFECTUEUX', 'Article défectueux')], default='', help_text='Code du motif choisi sur le terminal (ERREUR_COMMANDE / ARTICLE_DEFECTUEUX)', max_length=32),
        ),
    ]
